{#
    Link: link_kreditorenbeleg_kreditor
    Source Hub: hub_kreditorenbeleg (BELNR)
    Target Hub: hub_kreditor (KNR — Ghost Hub)
    Source: ewb_kred_kbl_main
    
    Verbindet einen Kreditorenbeleg mit dem zugehörigen Kreditor.
    KBL.KNR ist die Kreditoren-Nummer (FK zu hub_kreditor).
    
    Generated by vault-architect using automate_dv.link macro
    @see https://automate-dv.readthedocs.io/en/latest/tutorial/tut_links/

    Developer: Daniel Fellner, MSc
    Company:   ppmc analytics ag
    Contact:   office@ppmcag.com
    Version:   2026-03-30 V1.0 Initialversion (Wave 2 Finance)
#}

{{ config(
    materialized='incremental',
    as_columnstore=false,
    post_hook=["{{ create_hash_index('hk_link_kreditorenbeleg_kreditor') }}"]
) }}

{%- set yaml_metadata -%}
source_model: "ewb_kred_kbl_main"
src_pk: "hk_link_kreditorenbeleg_kreditor"
src_fk: 
    - "hk_kreditorenbeleg"
    - "hk_kreditor"
src_ldts: "dss_load_date"
src_source: "dss_record_source"
{%- endset -%}

{% set metadata_dict = fromyaml(yaml_metadata) %}

{{ automate_dv.link(
    src_pk=metadata_dict["src_pk"],
    src_fk=metadata_dict["src_fk"],
    src_ldts=metadata_dict["src_ldts"],
    src_source=metadata_dict["src_source"],
    source_model=metadata_dict["source_model"]
) }}
