{#
    Link: link_hauptbuch_buchungskopf
    Source Hub: hub_hauptbuch (GL.RECNUM)
    Target Hub: hub_buchungskopf (GL.DKBELEGNUMMER = FHE.RECNUM)
    Source: ewb_fibu_gl
    
    Verbindet eine Hauptbuch-Buchungszeile (GL) mit dem zugehörigen
    Buchungskopf (FHE). GL.DKBELEGNUMMER referenziert FHE.RECNUM.
    
    Generated by vault-architect using automate_dv.link macro
    @see https://automate-dv.readthedocs.io/en/latest/tutorial/tut_links/

    Developer: Daniel Fellner, MSc
    Company:   ppmc analytics ag
    Contact:   office@ppmcag.com
    Version:   2026-03-30 V1.0 Initialversion (Wave 2 Finance)
#}

{{ config(
    materialized='incremental',
    as_columnstore=false,
    post_hook=["{{ create_hash_index('hk_link_hauptbuch_buchungskopf') }}"]
) }}

{%- set yaml_metadata -%}
source_model: "ewb_fibu_gl"
src_pk: "hk_link_hauptbuch_buchungskopf"
src_fk: 
    - "hk_hauptbuch"
    - "hk_buchungskopf"
src_ldts: "dss_load_date"
src_source: "dss_record_source"
{%- endset -%}

{% set metadata_dict = fromyaml(yaml_metadata) %}

{{ automate_dv.link(
    src_pk=metadata_dict["src_pk"],
    src_fk=metadata_dict["src_fk"],
    src_ldts=metadata_dict["src_ldts"],
    src_source=metadata_dict["src_source"],
    source_model=metadata_dict["source_model"]
) }}
