{#
    Link: link_projektteil_projekt
    Source Hub: hub_projektteil (PRT.RECNUM)
    Target Hub: hub_projekt (PRT.PROJNR → NPO.PROJNR)
    Source: ewb_proj_prt_main

    Verbindet einen Projektteil (PRT) mit dem zugehoerigen
    Projekt (NPO). PRT.PROJNR referenziert NPO.PROJNR.
    Wave 3 — Projektteile.

    Generated by vault-architect using automate_dv.link macro
    @see https://automate-dv.readthedocs.io/en/latest/tutorial/tut_links/

    Developer: Daniel Fellner, MSc
    Company:   ppmc analytics ag
    Contact:   office@ppmcag.com
    Version:   2026-03-30 V1.0 Initialversion
#}

{{ config(
    materialized='incremental',
    as_columnstore=false,
    post_hook=["{{ create_hash_index('hk_link_projektteil_projekt') }}"]
) }}

{%- set yaml_metadata -%}
source_model: "ewb_proj_prt_main"
src_pk: "hk_link_projektteil_projekt"
src_fk: 
    - "hk_projektteil"
    - "hk_projekt"
src_ldts: "dss_load_date"
src_source: "dss_record_source"
{%- endset -%}

{% set metadata_dict = fromyaml(yaml_metadata) %}

{{ automate_dv.link(
    src_pk=metadata_dict["src_pk"],
    src_fk=metadata_dict["src_fk"],
    src_ldts=metadata_dict["src_ldts"],
    src_source=metadata_dict["src_source"],
    source_model=metadata_dict["source_model"]
) }}
