{#
    Link: link_hauptbuch_kreditor
    Source Hub: hub_hauptbuch (GL.RECNUM)
    Target Hub: hub_kreditor (GL.DKKUNDENNUMMER → KBL.KNR)
    Source: ewb_fibu_gl
    
    Verbindet eine Hauptbuch-Buchungszeile (GL) mit dem zugehörigen
    Kreditor. GL.DKKUNDENNUMMER referenziert KBL.KNR (Kreditoren-Nummer).
    
    Generated by vault-architect using automate_dv.link macro
    @see https://automate-dv.readthedocs.io/en/latest/tutorial/tut_links/

    Developer: Daniel Fellner, MSc
    Company:   ppmc analytics ag
    Contact:   office@ppmcag.com
    Version:   2026-03-30 V1.0 Initialversion (Wave 3 GL-Dimension-Links)
#}

{{ config(
    materialized='incremental',
    as_columnstore=false,
    post_hook=["{{ create_hash_index('hk_link_hauptbuch_kreditor') }}"]
) }}

{%- set yaml_metadata -%}
source_model: "ewb_fibu_gl"
src_pk: "hk_link_hauptbuch_kreditor"
src_fk: 
    - "hk_hauptbuch"
    - "hk_kreditor"
src_ldts: "dss_load_date"
src_source: "dss_record_source"
{%- endset -%}

{% set metadata_dict = fromyaml(yaml_metadata) %}

{{ automate_dv.link(
    src_pk=metadata_dict["src_pk"],
    src_fk=metadata_dict["src_fk"],
    src_ldts=metadata_dict["src_ldts"],
    src_source=metadata_dict["src_source"],
    source_model=metadata_dict["source_model"]
) }}
