{#
    Link: link_kreditorenbeleg_zahlung
    Source Hub: hub_kreditorenbeleg (BELNR)
    Target Hub: hub_zahlung (DOCUMENTNR+POSITIONNR+ELEMENTTYP+INR)
    Source: ewb_kred_kvl_main

    Verbindet einen Kreditorenbeleg mit den zugehoerigen Zahlungspositionen.
    KBL.BELNR = KVL.DOCUMENTNR (aus Synapse Finance.Belege abgeleitet).

    Generated by vault-architect using automate_dv.link macro
    @see https://automate-dv.readthedocs.io/en/latest/tutorial/tut_links/

    Developer: Daniel Fellner, MSc
    Company:   ppmc analytics ag
    Contact:   office@ppmcag.com
    Version:   2026-03-30 V1.0 Initialversion (Wave 3 Finance)
#}

{{ config(
    materialized='incremental',
    as_columnstore=false,
    post_hook=["{{ create_hash_index('hk_link_kreditorenbeleg_zahlung') }}"]
) }}

{%- set yaml_metadata -%}
source_model: "ewb_kred_kvl_main"
src_pk: "hk_link_kreditorenbeleg_zahlung"
src_fk:
    - "hk_kreditorenbeleg"
    - "hk_zahlung"
src_ldts: "dss_load_date"
src_source: "dss_record_source"
{%- endset -%}

{% set metadata_dict = fromyaml(yaml_metadata) %}

{{ automate_dv.link(
    src_pk=metadata_dict["src_pk"],
    src_fk=metadata_dict["src_fk"],
    src_ldts=metadata_dict["src_ldts"],
    src_source=metadata_dict["src_source"],
    source_model=metadata_dict["source_model"]
) }}
