{#
    Hub: hub_person
    Source: ewb_lohn_len_main
    Business Keys: EMPL_NR
    
    Generated by Entity Designer using automate_dv.hub macro
    @see https://automate-dv.readthedocs.io/en/latest/tutorial/tut_hubs/
#}

{{ config(
    materialized='incremental',
    as_columnstore=false,
    post_hook=["{{ create_hash_index('hk_person') }}"]
) }}

{%- set yaml_metadata -%}
source_model: "ewb_lohn_len_main"
src_pk: "hk_person"
src_nk: "empl_nr"
src_extra_columns:
    - "dss_business_key"
    - "dss_create_datetime"
src_ldts: "dss_load_date"
src_source: "dss_record_source"
{%- endset -%}

{% set metadata_dict = fromyaml(yaml_metadata) %}

{{ automate_dv.hub(
    src_pk=metadata_dict["src_pk"],
    src_nk=metadata_dict["src_nk"],
    src_extra_columns=metadata_dict["src_extra_columns"],
    src_ldts=metadata_dict["src_ldts"],
    src_source=metadata_dict["src_source"],
    source_model=metadata_dict["source_model"]
) }}
