{#
    Link: link_comments_seed_vorgang
    Parent Hub: jira.hub_vorgang
    Dependent Child: comments_seed (no own hub)
    Driving Key: issue_id
    Link Type: Dependent Child Link (Pure DC)
    - Source entity has no own Business Key
    - Identified by: Target FK (issue_id) + DCK (comment_author, comment_date)
    - Link PK hash includes DCK columns (calculated in staging)
    - DCK values are stored in the DC Satellite, not the link
    Source: jira_comments_seed
    
    Note: In automate_dv, links don't store payload columns.
    DCK columns are only used for the link hash calculation in staging.
    The actual DCK values are stored in the DC Satellite.
    
    Generated by Entity Designer using automate_dv.link macro
    @see https://automate-dv.readthedocs.io/en/latest/tutorial/tut_links/
#}

{{ config(
    materialized='incremental',
    as_columnstore=false
) }}

{%- set yaml_metadata -%}
source_model: "jira_comments_seed"
src_pk: "hk_link_comments_seed_vorgang"
src_fk: "hk_vorgang"
src_ldts: "dss_load_date"
src_source: "dss_record_source"
{%- endset -%}

{% set metadata_dict = fromyaml(yaml_metadata) %}

{{ automate_dv.link(
    src_pk=metadata_dict["src_pk"],
    src_fk=metadata_dict["src_fk"],
    src_ldts=metadata_dict["src_ldts"],
    src_source=metadata_dict["src_source"],
    source_model=metadata_dict["source_model"]
) }}
