/*
 * Staging Model: ewb_lohn_len_main
 *
 * Source: ext_ewb_lohn_len_main
 * Business Key: EMPL_NR
 * Hash Key Separator: '^^' (DV 2.1 Standard)
 *
 * Hash Keys calculated here (automate_dv pattern):
 *   - hk_lohn_len_main (Entity Hash Key)
 */

{%- set hashdiff_columns = [
    '_userfield1',
    '_userfield10',
    '_userfield11',
    '_userfield2',
    '_userfield3',
    '_userfield4',
    '_userfield5',
    '_userfield6',
    '_userfield7',
    '_userfield8',
    '_userfield9',
    'abaprgrp',
    'abrv',
    'act_lohn',
    'act_pis',
    'act_prj',
    'act_upps',
    'adr_inr',
    'agricultura_employee',
    'auto_approve_absence',
    'auto_approve_booking',
    'auto_approve_trip',
    'autodate',
    'badge_id',
    'birth_place',
    'birthday',
    'book_group',
    'bvg_code',
    'bvg_contribution',
    'bvg_deg_disability',
    'bvg_level_employment',
    'calc_group',
    'checks',
    'checkspis',
    'clearingtext_1',
    'clearingtext_2',
    'clearingtext_3',
    'clearingtext_4',
    'clearingtext_5',
    'code_1',
    'code_11',
    'code_2',
    'code_3',
    'code_7',
    'code_8',
    'code_9',
    'cons_nr',
    'contract',
    'contract_type',
    'date_1',
    'date_2',
    'date_3',
    'date_in',
    'date_out',
    'degree_rel_ship',
    'disable_for_empl_com',
    'email_category',
    'empl_id',
    'enterprise',
    'excluded_from_review',
    'first_name',
    'gb',
    'grp_lc',
    'hide_in_empl_dir',
    'home_dept_nr',
    'inr_placeofwork',
    'iso_code',
    'language_code',
    'last_name',
    'lat_nr',
    'law_codes',
    'law_exptyp',
    'len_date',
    'lpe_month',
    'lpe_year',
    'mutation_date',
    'mutations',
    'nation_id',
    'national_10',
    'national_2',
    'national_4',
    'national_5',
    'national_6',
    'national_7',
    'national_8',
    'national_code_1',
    'national_code_3',
    'national_code_4',
    'national_date_1',
    'national_id_1',
    'national_id_7',
    'national_id_8',
    'national_nr_5',
    'national_sw_1',
    'national_text',
    'nationality',
    'not_ful_fit_for_work',
    'nr_1',
    'nr_10',
    'nr_11',
    'nr_12',
    'nr_13',
    'nr_14',
    'nr_16',
    'nr_17',
    'nr_18',
    'nr_19',
    'nr_2',
    'nr_20',
    'nr_21',
    'nr_23',
    'nr_24',
    'nr_25',
    'nr_27',
    'nr_29',
    'nr_3',
    'nr_4',
    'nr_6',
    'nr_7',
    'nr_8',
    'nr_9',
    'nrl_1',
    'nrl_2',
    'oasi_exempt_pension',
    'part_retirement_date',
    'periodicity',
    'perm_staff_p_admin',
    'post_int_adr_tel',
    'post_int_adr1',
    'post_qual_grp',
    'proj_timemodel',
    'recnum',
    'relevant_for_logib',
    'retirement_date',
    'rhythm',
    'rights',
    'rightspis',
    'sex',
    'single_parent_family',
    'soc_insur_nr_unknown',
    'soc_insurance_nr',
    'sw_1',
    'sw_2',
    'sw_3',
    'sw_4',
    'sw_5',
    'sw_wifeworkinch',
    'sync_kvs',
    'syskey',
    'temp_agency_worker',
    'timestamp_landing-zone',
    'type',
    'type_of_max',
    'user_f',
    'vacation_acc_table',
    'value_1',
    'var_abrv',
    'var_text',
    'var_text2',
    'var_text3',
    'zar_nr',
    'zemis_nr'
] -%}

WITH source AS (
    SELECT * FROM {{ source('staging', 'ext_ewb_lohn_len_main') }}
),

staged AS (
    SELECT
        -- ===========================================
        -- HASH KEY (Entity)
        -- ===========================================
        CONVERT(CHAR(64), HASHBYTES('SHA2_256', 
            ISNULL(CAST(EMPL_NR AS NVARCHAR(MAX)), '')
        ), 2) AS hk_lohn_len_main,

        -- ===========================================
        -- HASH DIFF (Change Detection - Satellite)
        -- ===========================================
        CONVERT(CHAR(64), HASHBYTES('SHA2_256', 
            CONCAT(
                {%- for col in hashdiff_columns %}
                ISNULL(CAST({{ col }} AS NVARCHAR(MAX)), ''){{ ',' if not loop.last else '' }}
                {%- endfor %}
                {%- if hashdiff_columns | length == 1 %}, ''{%- endif %}
            )
        ), 2) AS hd_lohn_len_main,

        -- ===========================================
        -- BUSINESS KEY(S)
        -- ===========================================
        EMPL_NR,

        -- ===========================================
        -- PAYLOAD
        -- ===========================================
        syskey,
        recnum,
        empl_id,
        last_name,
        first_name,
        badge_id,
        home_dept_nr,
        calc_group,
        book_group,
        adr_inr,
        lpe_year,
        lpe_month,
        date_in,
        date_out,
        birthday,
        sex,
        rhythm,
        type,
        language_code,
        type_of_max,
        mutation_date,
        mutations,
        user_f,
        nation_id,
        iso_code,
        national_2,
        national_4,
        national_5,
        national_6,
        national_7,
        national_8,
        national_10,
        national_nr_5,
        national_id_1,
        national_id_7,
        national_id_8,
        national_sw_1,
        national_code_1,
        national_code_3,
        national_code_4,
        national_text,
        national_date_1,
        abrv,
        nationality,
        birth_place,
        var_abrv,
        var_text,
        nr_1,
        nr_2,
        nr_3,
        nr_4,
        nr_6,
        nr_7,
        nr_8,
        nr_9,
        nr_10,
        code_1,
        code_2,
        code_3,
        code_7,
        code_8,
        code_9,
        date_1,
        date_2,
        date_3,
        inr_placeofwork,
        periodicity,
        retirement_date,
        not_ful_fit_for_work,
        bvg_code,
        bvg_contribution,
        soc_insur_nr_unknown,
        oasi_exempt_pension,
        bvg_level_employment,
        bvg_deg_disability,
        part_retirement_date,
        disable_for_empl_com,
        excluded_from_review,
        hide_in_empl_dir,
        cons_nr,
        rights,
        checks,
        rightspis,
        checkspis,
        gb,
        enterprise,
        single_parent_family,
        auto_approve_absence,
        auto_approve_booking,
        auto_approve_trip,
        email_category,
        vacation_acc_table,
        act_upps,
        abaprgrp,
        law_codes,
        law_exptyp,
        act_lohn,
        act_pis,
        act_prj,
        grp_lc,
        sync_kvs,
        autodate,
        proj_timemodel,
        lat_nr,
        agricultura_employee,
        degree_rel_ship,
        sw_wifeworkinch,
        soc_insurance_nr,
        nr_11,
        nr_12,
        nr_13,
        nr_14,
        zar_nr,
        zemis_nr,
        contract,
        contract_type,
        sw_1,
        sw_2,
        sw_3,
        sw_4,
        sw_5,
        code_11,
        nr_16,
        nr_17,
        nr_18,
        nr_19,
        nr_20,
        nrl_1,
        nrl_2,
        value_1,
        nr_21,
        nr_23,
        nr_24,
        nr_25,
        var_text2,
        var_text3,
        post_int_adr1,
        post_int_adr_tel,
        post_qual_grp,
        clearingtext_1,
        clearingtext_2,
        clearingtext_3,
        clearingtext_4,
        clearingtext_5,
        nr_27,
        nr_29,
        relevant_for_logib,
        perm_staff_p_admin,
        temp_agency_worker,
        len_date,
        _userfield1,
        _userfield2,
        _userfield3,
        _userfield4,
        _userfield5,
        _userfield6,
        _userfield7,
        _userfield8,
        _userfield9,
        _userfield10,
        _userfield11,
        timestamp_landing-zone,

        -- ===========================================
        -- METADATA
        -- ===========================================
        COALESCE(dss_record_source, 'ewb') AS dss_record_source,
        COALESCE(TRY_CAST(dss_load_date AS DATETIME2), GETDATE()) AS dss_load_date,
        dss_run_id

    FROM source
)

SELECT * FROM staged