/*
 * Staging Model: ewb_fibu_gl
 *
 * Source: ext_ewb_fibu_gl (Abacus FIBU/GL — Folder-Scan aller Jahresscheiben E22-E26+)
 * Business Key: RECNUM (unique row identifier — DKBELEGNUMMER+KTO ist NICHT unique)
 * Hash Key: hk_hauptbuch
 * Payload: 178 Spalten — Hauptbuch-Buchungszeilen (Soll/Haben)
 *
 * Note: SQL Server reserved keywords (DATE, TEXT) handled via derived_columns escape mechanism.
 *
 * BK-Entscheidung (29.3.2026): DKBELEGNUMMER+KTO hat 62% Nullen und bis zu 96 Duplikate
 * pro Kombination. RECNUM ist der einzig unique Identifier auf Zeilenebene.
 *
 * Link Hash Keys:
 *   - hk_buchungskopf:  DKBELEGNUMMER → hub_buchungskopf (FHE.RECNUM = GL.DKBELEGNUMMER)
 *   - hk_kreditor:      DKKUNDENNUMMER → hub_kreditor
 *   - hk_konto:         KTO → hub_konto (Ghost Hub)
 *   - hk_kostenstelle:  KST → hub_kostenstelle (Ghost Hub)
 *   - hk_projekt:       PROJ → hub_projekt
 *   - hk_link_hauptbuch_buchungskopf: [RECNUM, DKBELEGNUMMER]
 *
 * Uses automate_dv.stage() macro for standardized staging.
 */

{%- set yaml_metadata -%}
source_model:
  staging: "ext_ewb_fibu_gl"

derived_columns:
  dss_record_source: "!ewb_abacus"
  dss_load_date: "COALESCE(TRY_CAST(dss_load_date AS DATETIME2), GETDATE())"
  dss_create_datetime: "GETDATE()"
  dss_business_key: "CONCAT_WS('||', 'default', 'default', ISNULL(LTRIM(RTRIM(CAST(RECNUM AS NVARCHAR(MAX)))), '-1'))"
  _escape:
    source_column:
      - "DATE"
      - "TEXT"
      - "timestamp_landing-zone"
    escape: true

hashed_columns:
  hk_hauptbuch: "RECNUM"
  hk_buchungskopf: "DKBELEGNUMMER"
  hk_kreditor: "DKKUNDENNUMMER"
  hk_konto: "KTO"
  hk_kostenstelle: "KST"
  hk_projekt: "PROJ"
  hk_link_hauptbuch_buchungskopf:
    - "RECNUM"
    - "DKBELEGNUMMER"
  hd_hauptbuch:
    is_hashdiff: true
    columns:
      - "A1"
      - "A3"
      - "A4"
      - "ABEAAUFTRAGNR"
      - "ABEARUECKNR"
      - "ABGRENZBIS"
      - "ABGRENZID"
      - "ABGRENZNR"
      - "ABGRENZVON"
      - "ACCESSID"
      - "ADDRESS"
      - "ANSATZ"
      - "AUFTRNR"
      - "B2BARID"
      - "BDATE"
      - "BELNR"
      - "BETRAG"
      - "BUDOVERARID"
      - "BUGUID"
      - "BUREL"
      - "CLEARINGARIDCREDIT"
      - "CLEARINGARIDDEBIT"
      - "CLEARINGTEXT"
      - "CODE"
      - "COMPANY"
      - "COMPANY2"
      - "CONTRADIVARID"
      - "CONTRADIVGKTO"
      - "CONTRADIVGUID"
      - "CONTRADIVID"
      - "CONTRADIVINVDATE"
      - "CONTRADIVKTO"
      - "DATE"
      - "DATE1"
      - "DEB_ASCII"
      - "DEB_NUM1"
      - "DEB_NUM2"
      - "DEB_NUM3"
      - "DETAILPLAN"
      - "DIVISION"
      - "DKKUNDENNUMMER"
      - "DKPOSNUMMER"
      - "DRUCK"
      - "EBSORT"
      - "ELIARID"
      - "ELIGRPNR"
      - "ENTERPRISE"
      - "EURKOEF1"
      - "EURKOEF2"
      - "FBETR"
      - "FBETR2"
      - "FBUCHART"
      - "FDK"
      - "FOND1"
      - "FOND2"
      - "FREMDIDBEZEICHNUNG"
      - "FREMDIDNUMMER"
      - "FRW"
      - "FUPBUSINESSCASE"
      - "FUPENTRYSET"
      - "FUPGUID"
      - "FUPID"
      - "FWAUTO"
      - "FWWHO"
      - "GATTUNG"
      - "GKART_REF"
      - "GKTO"
      - "GPROJ"
      - "GPROJEBENE"
      - "GROBPLAN"
      - "GUID1"
      - "IMMOGB"
      - "IMMO_ABR_ABR_DAT"
      - "IMMO_ABR_ABR_DAT_2"
      - "IMMO_ABR_ART"
      - "IMMO_HKNK_DAT"
      - "INVEANLAGENNR"
      - "INVEBA"
      - "INVEBUPOSRF"
      - "INVEID"
      - "INVEVB"
      - "INVEVBART"
      - "ISO"
      - "ISO2"
      - "ISREMOTEUSER"
      - "KART"
      - "KART_REF"
      - "KAT1"
      - "KAT2"
      - "KFR"
      - "KONSCODE"
      - "KONSMUARID"
      - "KONSTOARID"
      - "KOREBASIS"
      - "KORR"
      - "KORRGUID"
      - "KST"
      - "KST2"
      - "KSTNR"
      - "KURS2"
      - "KURSARID"
      - "K_BETRAG"
      - "MANDANT"
      - "MATCH1"
      - "MENGE"
      - "MENGE_BEZ"
      - "MERCHANTCATEGORYCODE"
      - "MERCHANTCATEGORYGRP"
      - "MWSTARID"
      - "MWSTARIDAUSLAND"
      - "MWSTAUTOARID"
      - "MWSTAUTOARIDTYP"
      - "MWSTBETR"
      - "MWSTCODE"
      - "MWSTFWBETR"
      - "MWSTFWISO"
      - "MWSTINCL"
      - "MWSTJAHR"
      - "MWSTKFR1"
      - "MWSTKFR2"
      - "MWSTKOEFF"
      - "MWSTKTO"
      - "MWSTKTO2"
      - "MWSTKTOBETR"
      - "MWSTKTOISO"
      - "MWSTKTOKURS"
      - "MWSTKTORESTBETR"
      - "MWSTLAND"
      - "MWSTMETH"
      - "MWSTMONAT"
      - "MWSTREV"
      - "MWSTSATZ"
      - "MWSTSH"
      - "MWSTTYP"
      - "N2"
      - "NUMRES3"
      - "NUMRES4"
      - "ORGSTAPEL"
      - "OUTARID"
      - "PANR"
      - "PROJ"
      - "PROJEBENE"
      - "PROZWERT"
      - "REC"
      - "RECNUM"
      - "RESTBETR"
      - "RESTFWBETR"
      - "SAM"
      - "SAMGUID"
      - "SAMNR"
      - "SH"
      - "SOLLIST"
      - "SPEC1"
      - "SPEC2"
      - "STAPEL"
      - "SYSKEY"
      - "TEXT"
      - "TEXT2"
      - "VDATE"
      - "VERSION"
      - "VISIERT"
      - "WAEHR"
      - "ZIELABGRENZBIS"
      - "ZIELABGRENZNR"
      - "ZIELABGRENZVON"
      - "ZIELGBKST"
      - "ZIELGBKTO"
      - "ZIELGBMWSTBETR"
      - "ZIELGBMWSTCODE"
      - "ZIELGBMWSTFWBETR"
      - "ZIELGBMWSTINCL"
      - "ZIELGBMWSTKOEFF"
      - "ZIELGBMWSTSATZ"
      - "ZIELGBPRO"
      - "ZIELGBPROJ"
      - "ZIELGBRESTBETR"
      - "ZIELGBRESTFWBETR"
      - "ZINSARID"
{%- endset -%}

{% set metadata_dict = fromyaml(yaml_metadata) %}

{{ automate_dv.stage(include_source_columns=true,
                     source_model=metadata_dict['source_model'],
                     derived_columns=metadata_dict['derived_columns'],
                     hashed_columns=metadata_dict['hashed_columns']) }}
