version: 2
sources:
  - name: "staging"
    description: "External Tables über PolyBase (Parquet aus ADLS)"
    database: "{{ target.database }}"
    schema: "stg"
    tables:
      - name: "ext_adventureworks_customer"
        description: "AdventureWorks SalesLT.Customer"
        external:
          location: "adventureworks/sqlserver/SalesLT.Customer.parquet"
          file_format: "ParquetFormat"
          data_source: "StageFileSystem"
        columns:
          - name: "CustomerID"
            data_type: "INT"
          - name: "NameStyle"
            data_type: "BIT"
          - name: "Title"
            data_type: "NVARCHAR(4000)"
          - name: "FirstName"
            data_type: "NVARCHAR(4000)"
          - name: "MiddleName"
            data_type: "NVARCHAR(4000)"
          - name: "LastName"
            data_type: "NVARCHAR(4000)"
          - name: "Suffix"
            data_type: "NVARCHAR(4000)"
          - name: "CompanyName"
            data_type: "NVARCHAR(4000)"
          - name: "SalesPerson"
            data_type: "NVARCHAR(4000)"
          - name: "EmailAddress"
            data_type: "NVARCHAR(4000)"
          - name: "Phone"
            data_type: "NVARCHAR(4000)"
          - name: "PasswordHash"
            data_type: "NVARCHAR(4000)"
          - name: "PasswordSalt"
            data_type: "NVARCHAR(4000)"
          - name: "rowguid"
            data_type: "NVARCHAR(4000)"
          - name: "ModifiedDate"
            data_type: "DATETIME2"
          - name: "dss_record_source"
            data_type: "NVARCHAR(4000)"
          - name: "dss_load_date"
            data_type: "NVARCHAR(4000)"
          - name: "dss_run_id"
            data_type: "NVARCHAR(4000)"
      - name: "ext_werkportal_public_wp_company_client"
        description: "Auto-generated from public.wp_company_client.parquet"
        external:
          location: "werkportal/postgres/public.wp_company_client.parquet"
          file_format: "ParquetFormat"
          data_source: "StageFileSystem"
        columns:
          - name: "object_id"
            data_type: "BIGINT"
          - name: "date_created"
            data_type: "DATETIME2"
          - name: "date_updated"
            data_type: "DATETIME2"
          - name: "subscription"
            data_type: "NVARCHAR(4000)"
          - name: "name"
            data_type: "NVARCHAR(4000)"
          - name: "state"
            data_type: "NVARCHAR(4000)"
          - name: "citycode"
            data_type: "NVARCHAR(4000)"
          - name: "city"
            data_type: "NVARCHAR(4000)"
          - name: "website"
            data_type: "NVARCHAR(4000)"
          - name: "street"
            data_type: "NVARCHAR(4000)"
          - name: "province"
            data_type: "NVARCHAR(4000)"
          - name: "credit_rating"
            data_type: "NVARCHAR(4000)"
          - name: "country"
            data_type: "BIGINT"
          - name: "employeecount"
            data_type: "DECIMAL(38,10)"
          - name: "email"
            data_type: "NVARCHAR(4000)"
          - name: "commission_fee"
            data_type: "NVARCHAR(4000)"
          - name: "phone"
            data_type: "NVARCHAR(4000)"
          - name: "mobile"
            data_type: "NVARCHAR(4000)"
          - name: "mobile2"
            data_type: "NVARCHAR(4000)"
          - name: "bic"
            data_type: "NVARCHAR(4000)"
          - name: "fax"
            data_type: "NVARCHAR(4000)"
          - name: "iban"
            data_type: "NVARCHAR(4000)"
          - name: "description"
            data_type: "NVARCHAR(4000)"
          - name: "org_type"
            data_type: "BIGINT"
          - name: "uid"
            data_type: "NVARCHAR(4000)"
          - name: "freistellungsbescheinigung"
            data_type: "DATETIME2"
          - name: "dss_record_source"
            data_type: "NVARCHAR(4000)"
          - name: "dss_load_date"
            data_type: "NVARCHAR(4000)"
          - name: "dss_run_id"
            data_type: "NVARCHAR(4000)"
          - name: "dss_stage_timestamp"
            data_type: "NVARCHAR(4000)"
          - name: "dss_source_file_name"
            data_type: "NVARCHAR(4000)"
      - name: "ext_werkportal_public_wp_company_contractor"
        description: "Auto-generated from public.wp_company_contractor.parquet"
        external:
          location: "werkportal/postgres/public.wp_company_contractor.parquet"
          file_format: "ParquetFormat"
          data_source: "StageFileSystem"
        columns:
          - name: "object_id"
            data_type: "BIGINT"
          - name: "date_created"
            data_type: "DATETIME2"
          - name: "date_updated"
            data_type: "DATETIME2"
          - name: "subscription"
            data_type: "NVARCHAR(4000)"
          - name: "name"
            data_type: "NVARCHAR(4000)"
          - name: "state"
            data_type: "NVARCHAR(4000)"
          - name: "citycode"
            data_type: "NVARCHAR(4000)"
          - name: "city"
            data_type: "NVARCHAR(4000)"
          - name: "website"
            data_type: "NVARCHAR(4000)"
          - name: "street"
            data_type: "NVARCHAR(4000)"
          - name: "province"
            data_type: "NVARCHAR(4000)"
          - name: "credit_rating"
            data_type: "NVARCHAR(4000)"
          - name: "country"
            data_type: "BIGINT"
          - name: "employeecount"
            data_type: "DECIMAL(38,10)"
          - name: "email"
            data_type: "NVARCHAR(4000)"
          - name: "commission_fee"
            data_type: "NVARCHAR(4000)"
          - name: "phone"
            data_type: "NVARCHAR(4000)"
          - name: "mobile"
            data_type: "NVARCHAR(4000)"
          - name: "mobile2"
            data_type: "NVARCHAR(4000)"
          - name: "bic"
            data_type: "NVARCHAR(4000)"
          - name: "fax"
            data_type: "NVARCHAR(4000)"
          - name: "iban"
            data_type: "NVARCHAR(4000)"
          - name: "description"
            data_type: "NVARCHAR(4000)"
          - name: "org_type"
            data_type: "BIGINT"
          - name: "uid"
            data_type: "NVARCHAR(4000)"
          - name: "dss_record_source"
            data_type: "NVARCHAR(4000)"
          - name: "dss_load_date"
            data_type: "NVARCHAR(4000)"
          - name: "dss_run_id"
            data_type: "NVARCHAR(4000)"
          - name: "dss_stage_timestamp"
            data_type: "NVARCHAR(4000)"
          - name: "dss_source_file_name"
            data_type: "NVARCHAR(4000)"
      - name: "ext_werkportal_public_wp_company_supplier"
        description: "Auto-generated from public.wp_company_supplier.parquet"
        external:
          location: "werkportal/postgres/public.wp_company_supplier.parquet"
          file_format: "ParquetFormat"
          data_source: "StageFileSystem"
        columns:
          - name: "object_id"
            data_type: "BIGINT"
          - name: "date_created"
            data_type: "DATETIME2"
          - name: "date_updated"
            data_type: "DATETIME2"
          - name: "subscription"
            data_type: "NVARCHAR(4000)"
          - name: "name"
            data_type: "NVARCHAR(4000)"
          - name: "state"
            data_type: "NVARCHAR(4000)"
          - name: "citycode"
            data_type: "NVARCHAR(4000)"
          - name: "city"
            data_type: "NVARCHAR(4000)"
          - name: "website"
            data_type: "NVARCHAR(4000)"
          - name: "street"
            data_type: "NVARCHAR(4000)"
          - name: "province"
            data_type: "NVARCHAR(4000)"
          - name: "credit_rating"
            data_type: "NVARCHAR(4000)"
          - name: "country"
            data_type: "BIGINT"
          - name: "employeecount"
            data_type: "DECIMAL(38,10)"
          - name: "email"
            data_type: "NVARCHAR(4000)"
          - name: "commission_fee"
            data_type: "NVARCHAR(4000)"
          - name: "phone"
            data_type: "NVARCHAR(4000)"
          - name: "mobile"
            data_type: "NVARCHAR(4000)"
          - name: "mobile2"
            data_type: "NVARCHAR(4000)"
          - name: "bic"
            data_type: "NVARCHAR(4000)"
          - name: "fax"
            data_type: "NVARCHAR(4000)"
          - name: "iban"
            data_type: "NVARCHAR(4000)"
          - name: "description"
            data_type: "NVARCHAR(4000)"
          - name: "org_type"
            data_type: "BIGINT"
          - name: "uid"
            data_type: "NVARCHAR(4000)"
          - name: "dss_record_source"
            data_type: "NVARCHAR(4000)"
          - name: "dss_load_date"
            data_type: "NVARCHAR(4000)"
          - name: "dss_run_id"
            data_type: "NVARCHAR(4000)"
          - name: "dss_stage_timestamp"
            data_type: "NVARCHAR(4000)"
          - name: "dss_source_file_name"
            data_type: "NVARCHAR(4000)"
      - name: "ext_werkportal_public_wp_contacts"
        description: "Auto-generated from public.wp_contacts.parquet"
        external:
          location: "werkportal/postgres/public.wp_contacts.parquet"
          file_format: "ParquetFormat"
          data_source: "StageFileSystem"
        columns:
          - name: "object_id"
            data_type: "BIGINT"
          - name: "date_created"
            data_type: "DATETIME2"
          - name: "date_updated"
            data_type: "DATETIME2"
          - name: "subscription"
            data_type: "NVARCHAR(4000)"
          - name: "name"
            data_type: "NVARCHAR(4000)"
          - name: "state"
            data_type: "NVARCHAR(4000)"
          - name: "title"
            data_type: "NVARCHAR(4000)"
          - name: "email1"
            data_type: "NVARCHAR(4000)"
          - name: "email2"
            data_type: "NVARCHAR(4000)"
          - name: "mobile1"
            data_type: "NVARCHAR(4000)"
          - name: "mobile2"
            data_type: "NVARCHAR(4000)"
          - name: "phone"
            data_type: "NVARCHAR(4000)"
          - name: "fax"
            data_type: "NVARCHAR(4000)"
          - name: "contact_function_name"
            data_type: "NVARCHAR(4000)"
          - name: "company_supplier"
            data_type: "BIGINT"
          - name: "company_client"
            data_type: "BIGINT"
          - name: "company_contractor"
            data_type: "BIGINT"
          - name: "contact_function_id"
            data_type: "INT"
          - name: "dss_record_source"
            data_type: "NVARCHAR(4000)"
          - name: "dss_load_date"
            data_type: "NVARCHAR(4000)"
          - name: "dss_run_id"
            data_type: "NVARCHAR(4000)"
          - name: "dss_stage_timestamp"
            data_type: "NVARCHAR(4000)"
          - name: "dss_source_file_name"
            data_type: "NVARCHAR(4000)"
