version: 2

sources:
  - name: staging
    description: "External Tables über PolyBase (Parquet aus ADLS)"
    database: "{{ target.database }}"
    schema: stg
    
    # ===========================================
    # dbt-external-tables Konfiguration
    # ===========================================
    # Docs: https://github.com/dbt-labs/dbt-external-tables
    # Ausführen: dbt run-operation stage_external_sources
    # ===========================================
    
    tables:
      - name: ext_company_client
        description: "Werkportal Company Client - External Table"
        external:
          location: "werkportal/postgres/public.wp_company_client.parquet"
          file_format: ParquetFormat
          data_source: StageFileSystem
        columns:
          - name: object_id
            data_type: BIGINT
            description: "Business Key - Primärschlüssel aus Quellsystem"
            tests:
              - not_null
          - name: date_created
            data_type: DATETIME2
          - name: date_updated
            data_type: DATETIME2
          - name: subscription
            data_type: NVARCHAR(4000)
          - name: name
            data_type: NVARCHAR(4000)
          - name: state
            data_type: NVARCHAR(4000)
          - name: citycode
            data_type: NVARCHAR(4000)
          - name: city
            data_type: NVARCHAR(4000)
          - name: website
            data_type: NVARCHAR(4000)
          - name: street
            data_type: NVARCHAR(4000)
          - name: province
            data_type: NVARCHAR(4000)
          - name: credit_rating
            data_type: NVARCHAR(4000)
          - name: country
            data_type: BIGINT
            description: "FK zu countries"
          - name: employeecount
            data_type: "NUMERIC(38,0)"
          - name: email
            data_type: NVARCHAR(4000)
          - name: commission_fee
            data_type: NVARCHAR(4000)
          - name: phone
            data_type: NVARCHAR(4000)
          - name: mobile
            data_type: NVARCHAR(4000)
          - name: mobile2
            data_type: NVARCHAR(4000)
          - name: bic
            data_type: NVARCHAR(4000)
          - name: fax
            data_type: NVARCHAR(4000)
          - name: iban
            data_type: NVARCHAR(4000)
          - name: description
            data_type: NVARCHAR(4000)
          - name: org_type
            data_type: BIGINT
          - name: uid
            data_type: NVARCHAR(4000)
          - name: freistellungsbescheinigung
            data_type: DATETIME2
          - name: dss_record_source
            data_type: NVARCHAR(4000)
            description: "Datenquelle"
          - name: dss_load_date
            data_type: NVARCHAR(4000)
            description: "Ladedatum"
          - name: dss_run_id
            data_type: NVARCHAR(4000)
            description: "Pipeline Run ID"
          - name: dss_stage_timestamp
            data_type: NVARCHAR(4000)
          - name: dss_source_file_name
            data_type: NVARCHAR(4000)

      # ===========================================
      # TODO: Weitere External Tables
      # ===========================================
      
      - name: ext_countries
        description: "Werkportal Countries - External Table"
        external:
          location: "werkportal/postgres/public.wp_countries.parquet"
          file_format: ParquetFormat
          data_source: StageFileSystem
        columns:
          - name: object_id
            data_type: BIGINT
            description: "Business Key"
          - name: name
            data_type: NVARCHAR(4000)
          - name: dss_record_source
            data_type: NVARCHAR(4000)
          - name: dss_load_date
            data_type: NVARCHAR(4000)
          - name: dss_run_id
            data_type: NVARCHAR(4000)

      - name: ext_company_contractor
        description: "Werkportal Company Contractor - External Table"
        external:
          location: "werkportal/postgres/public.wp_company_contractor.parquet"
          file_format: ParquetFormat
          data_source: StageFileSystem
        columns:
          - name: object_id
            data_type: BIGINT
            description: "Business Key"
          - name: date_created
            data_type: DATETIME2
          - name: date_updated
            data_type: DATETIME2
          - name: subscription
            data_type: NVARCHAR(4000)
          - name: name
            data_type: NVARCHAR(4000)
          - name: state
            data_type: NVARCHAR(4000)
          - name: citycode
            data_type: NVARCHAR(4000)
          - name: city
            data_type: NVARCHAR(4000)
          - name: website
            data_type: NVARCHAR(4000)
          - name: street
            data_type: NVARCHAR(4000)
          - name: province
            data_type: NVARCHAR(4000)
          - name: credit_rating
            data_type: NVARCHAR(4000)
          - name: country
            data_type: BIGINT
          - name: employeecount
            data_type: "NUMERIC(38,18)"
          - name: email
            data_type: NVARCHAR(4000)
          - name: commission_fee
            data_type: NVARCHAR(4000)
          - name: phone
            data_type: NVARCHAR(4000)
          - name: mobile
            data_type: NVARCHAR(4000)
          - name: mobile2
            data_type: NVARCHAR(4000)
          - name: bic
            data_type: NVARCHAR(4000)
          - name: fax
            data_type: NVARCHAR(4000)
          - name: iban
            data_type: NVARCHAR(4000)
          - name: description
            data_type: NVARCHAR(4000)
          - name: org_type
            data_type: BIGINT
          - name: uid
            data_type: NVARCHAR(4000)
          - name: dss_record_source
            data_type: NVARCHAR(4000)
          - name: dss_load_date
            data_type: NVARCHAR(4000)
          - name: dss_run_id
            data_type: NVARCHAR(4000)
          - name: dss_stage_timestamp
            data_type: NVARCHAR(4000)
          - name: dss_source_file_name
            data_type: NVARCHAR(4000)

      - name: ext_company_supplier
        description: "Werkportal Company Supplier - External Table"
        external:
          location: "werkportal/postgres/public.wp_company_supplier.parquet"
          file_format: ParquetFormat
          data_source: StageFileSystem
        columns:
          - name: object_id
            data_type: BIGINT
            description: "Business Key"
          - name: date_created
            data_type: DATETIME2
          - name: date_updated
            data_type: DATETIME2
          - name: subscription
            data_type: NVARCHAR(4000)
          - name: name
            data_type: NVARCHAR(4000)
          - name: state
            data_type: NVARCHAR(4000)
          - name: citycode
            data_type: NVARCHAR(4000)
          - name: city
            data_type: NVARCHAR(4000)
          - name: website
            data_type: NVARCHAR(4000)
          - name: street
            data_type: NVARCHAR(4000)
          - name: province
            data_type: NVARCHAR(4000)
          - name: credit_rating
            data_type: NVARCHAR(4000)
          - name: country
            data_type: BIGINT
          - name: employeecount
            data_type: "NUMERIC(38,18)"
          - name: email
            data_type: NVARCHAR(4000)
          - name: commission_fee
            data_type: NVARCHAR(4000)
          - name: phone
            data_type: NVARCHAR(4000)
          - name: mobile
            data_type: NVARCHAR(4000)
          - name: mobile2
            data_type: NVARCHAR(4000)
          - name: bic
            data_type: NVARCHAR(4000)
          - name: fax
            data_type: NVARCHAR(4000)
          - name: iban
            data_type: NVARCHAR(4000)
          - name: description
            data_type: NVARCHAR(4000)
          - name: org_type
            data_type: BIGINT
          - name: uid
            data_type: NVARCHAR(4000)
          - name: dss_record_source
            data_type: NVARCHAR(4000)
          - name: dss_load_date
            data_type: NVARCHAR(4000)
          - name: dss_run_id
            data_type: NVARCHAR(4000)
          - name: dss_stage_timestamp
            data_type: NVARCHAR(4000)
          - name: dss_source_file_name
            data_type: NVARCHAR(4000)
      # ===========================================
      # Project (Projekte/Aufträge)
      # ===========================================
      - name: ext_project
        description: "Werkportal Project Overview - External Table"
        external:
          location: "werkportal/postgres/public.wp_project_overview.parquet"
          file_format: ParquetFormat
          data_source: StageFileSystem
        columns:
          - name: object_id
            data_type: BIGINT
            description: "Business Key - Primärschlüssel aus Quellsystem"
            tests:
              - not_null
          - name: user_created
            data_type: NVARCHAR(4000)
          - name: date_created
            data_type: DATETIME2
          - name: user_updated
            data_type: NVARCHAR(4000)
          - name: date_updated
            data_type: DATETIME2
          - name: subscription
            data_type: NVARCHAR(4000)
          - name: name
            data_type: NVARCHAR(4000)
            description: "Projektname"
          - name: state
            data_type: NVARCHAR(4000)
            description: "Projektstatus"
          - name: begin
            data_type: DATETIME2
            description: "Projektbeginn"
          - name: location
            data_type: NVARCHAR(4000)
            description: "Projektstandort"
          - name: price
            data_type: NUMERIC(38,18)
            description: "Projektpreis"
          - name: commission
            data_type: NUMERIC(38,18)
            description: "Provision"
          - name: end
            data_type: DATETIME2
            description: "Projektende"
          - name: work_begin
            data_type: NVARCHAR(4000)
          - name: author_email
            data_type: NVARCHAR(4000)
          - name: description
            data_type: NVARCHAR(4000)
          - name: price_units_value
            data_type: NVARCHAR(4000)
          - name: commission_units_value
            data_type: NVARCHAR(4000)
          - name: details
            data_type: NVARCHAR(4000)
          - name: user
            data_type: BIGINT
            description: "FK zu User"
          - name: provision_charged_state
            data_type: NVARCHAR(4000)
          - name: contractor_count
            data_type: INT
            description: "Anzahl Contractors"
          - name: client
            data_type: BIGINT
            description: "FK zu Company Client"
          - name: contractor
            data_type: BIGINT
            description: "FK zu Company Contractor"
          - name: member
            data_type: NVARCHAR(4000)
          - name: hidden
            data_type: BIT
          - name: is_contracting
            data_type: BIT
          - name: dss_record_source
            data_type: NVARCHAR(4000)
          - name: dss_load_date
            data_type: NVARCHAR(4000)
          - name: dss_run_id
            data_type: NVARCHAR(4000)
          - name: dss_stage_timestamp
            data_type: NVARCHAR(4000)
          - name: dss_source_file_name
            data_type: NVARCHAR(4000)

      # ===========================================
      # Invoice (Rechnungen)
      # ===========================================
      - name: ext_invoice
        description: "Werkportal Invoices - External Table"
        external:
          location: "werkportal/postgres/public.wp_invoices.parquet"
          file_format: ParquetFormat
          data_source: StageFileSystem
        columns:
          - name: object_id
            data_type: BIGINT
            description: "Business Key - Primärschlüssel aus Quellsystem"
            tests:
              - not_null
          - name: date_created
            data_type: DATETIME2
          - name: date_updated
            data_type: DATETIME2
          - name: subscription
            data_type: NVARCHAR(4000)
          - name: name
            data_type: NVARCHAR(4000)
            description: "Rechnungsname/-nummer"
          - name: state
            data_type: NVARCHAR(4000)
            description: "Rechnungsstatus"
          - name: deductions_description
            data_type: NVARCHAR(4000)
            description: "Beschreibung der Abzüge"
          - name: gross
            data_type: BIT
            description: "Brutto-Flag"
          - name: invoicing_period_year
            data_type: "NUMERIC(38,18)"
            description: "Abrechnungsjahr"
          - name: project
            data_type: BIGINT
            description: "FK zu Project"
          - name: invoice_date
            data_type: DATETIME2
            description: "Rechnungsdatum"
          - name: date_payed
            data_type: DATETIME2
            description: "Zahlungsdatum"
          - name: description
            data_type: NVARCHAR(4000)
            description: "Beschreibung"
          - name: advance_payment
            data_type: BIT
            description: "Vorauszahlung-Flag"
          - name: date_payed_internally
            data_type: DATETIME2
            description: "Internes Zahlungsdatum"
          - name: payed
            data_type: NVARCHAR(4000)
            description: "Bezahlt-Status"
          - name: contractor
            data_type: BIGINT
            description: "FK zu Company Contractor"
          - name: client
            data_type: BIGINT
            description: "FK zu Company Client"
          - name: sum_goal
            data_type: "NUMERIC(38,18)"
            description: "Zielsumme"
          - name: credit_period
            data_type: "NUMERIC(38,18)"
            description: "Zahlungsziel (Tage)"
          - name: deductions
            data_type: "NUMERIC(38,18)"
            description: "Abzüge"
          - name: sum_payed
            data_type: "NUMERIC(38,18)"
            description: "Bezahlte Summe"
          - name: hours_worked
            data_type: "NUMERIC(38,18)"
            description: "Gearbeitete Stunden"
          - name: subtractions
            data_type: "NUMERIC(38,18)"
            description: "Subtraktionen"
          - name: credit_rating_check
            data_type: "NUMERIC(38,18)"
            description: "Bonitätsprüfung"
          - name: discount
            data_type: "NUMERIC(38,18)"
            description: "Rabatt"
          - name: ordering
            data_type: "NUMERIC(38,18)"
            description: "Sortierung"
          - name: createdby
            data_type: NVARCHAR(4000)
            description: "Erstellt von"
          - name: member
            data_type: NVARCHAR(4000)
            description: "Zugeordnetes Mitglied"
          - name: pay_target_date
            data_type: DATETIME2
            description: "Zahlungszieldatum"
          - name: u_amount
            data_type: "NUMERIC(38,18)"
            description: "U-Betrag"
          - name: comission_amount
            data_type: "NUMERIC(38,18)"
            description: "Provisionsbetrag"
          - name: dss_record_source
            data_type: NVARCHAR(4000)
            description: "Datenquelle"
          - name: dss_load_date
            data_type: NVARCHAR(4000)
            description: "Ladedatum"
          - name: dss_run_id
            data_type: NVARCHAR(4000)
            description: "Pipeline Run ID"
          - name: dss_stage_timestamp
            data_type: NVARCHAR(4000)
          - name: dss_source_file_name
            data_type: NVARCHAR(4000)
