{#
    Satellite: sat_person
    Parent Hub: hub_person
    Source: ewb_lohn_len_main

    Payload (20 Spalten, datenbasiert bereinigt):
      Identität:   EMPL_ID, LAST_NAME, FIRST_NAME, ABRV, BADGE_ID, BIRTHDAY, SEX, NATIONALITY, BIRTH_PLACE
      Anstellung:  HOME_DEPT_NR, ADR_INR, DATE_IN, DATE_OUT, TYPE, MUTATION_DATE, LPE_YEAR, LPE_MONTH
      CH-SV:       SOC_INSURANCE_NR
      Compliance:  RELEVANT_FOR_LOGIB, ZEMIS_NR

    Entfernt (konstante/leere Felder):
      - CALC_GROUP, BOOK_GROUP, CONTRACT, CONTRACT_TYPE → alle 0
      - BVG_CODE, BVG_CONTRIBUTION, BVG_LEVEL_EMPLOYMENT, BVG_DEG_DISABILITY → alle 0 oder konstant 1
      - OASI_EXEMPT_PENSION → alle 1 (konstant)
      - RETIREMENT_DATE, PART_RETIREMENT_DATE → alle NULL
      - RHYTHM, PERIODICITY, INRPLACEOFWORK, PROJ_TIMEMODEL → konstant/leer
      - NATIONAL_CODE_1, NATION_ID, ISO_CODE → leer oder konstant (CHF/CH)
      - LANGUAGE_CODE → alle "de"
      - ZAR_NR → nur 5 Einträge (0.2%)
      - PERM_STAFF_P_ADMIN, TEMP_AGENCY_WORKER, NOT_FUL_FIT_FOR_WORK, SINGLE_PARENT_FAMILY → alle 0
      - EMAIL_CATEGORY → alle 0

    Generated by Entity Designer using automate_dv.sat macro
    @see https://automate-dv.readthedocs.io/en/latest/tutorial/tut_satellites/
#}

{{ config(
    materialized='incremental',
    as_columnstore=false,
    post_hook=[
        "{{ create_hash_index('hk_person') }}",
        "{{ update_satellite_current_flag(this, 'hk_person') }}"
    ]
) }}

{%- set yaml_metadata -%}
source_model: "ewb_lohn_len_main"
src_pk: "hk_person"
src_hashdiff:
  source_column: "hd_person"
  alias: "hashdiff"
src_payload:
    - "empl_id"
    - "last_name"
    - "first_name"
    - "abrv"
    - "badge_id"
    - "birthday"
    - "sex"
    - "nationality"
    - "birth_place"
    - "home_dept_nr"
    - "adr_inr"
    - "date_in"
    - "date_out"
    - "type"
    - "mutation_date"
    - "lpe_year"
    - "lpe_month"
    - "soc_insurance_nr"
    - "relevant_for_logib"
    - "zemis_nr"
src_eff: "dss_load_date"
src_ldts: "dss_load_date"
src_source: "dss_record_source"
{%- endset -%}

{% set metadata_dict = fromyaml(yaml_metadata) %}

{{ automate_dv.sat(
    src_pk=metadata_dict["src_pk"],
    src_hashdiff=metadata_dict["src_hashdiff"],
    src_payload=metadata_dict["src_payload"],
    src_eff=metadata_dict["src_eff"],
    src_ldts=metadata_dict["src_ldts"],
    src_source=metadata_dict["src_source"],
    source_model=metadata_dict["source_model"]
) }}
