{#
    Satellite: sat_contractor
    Parent Hub: hub_contractor
    Source: werkportal_contractor
    Payload: date_created, date_updated, subscription, name, state, citycode, city, website, street, province, credit_rating, country, employeecount, email, commission_fee, phone, mobile, mobile2, bic, fax, iban, description, org_type, uid
    
    Generated by Entity Designer using automate_dv.sat macro
    @see https://automate-dv.readthedocs.io/en/latest/tutorial/tut_satellites/
#}

{{ config(
    materialized='incremental',
    as_columnstore=false
) }}

{%- set yaml_metadata -%}
source_model: "werkportal_contractor"
src_pk: "hk_contractor"
src_hashdiff: 
  source_column: "hd_contractor"
  alias: "hashdiff"
src_payload: 
    - "date_created"
    - "date_updated"
    - "subscription"
    - "name"
    - "state"
    - "citycode"
    - "city"
    - "website"
    - "street"
    - "province"
    - "credit_rating"
    - "country"
    - "employeecount"
    - "email"
    - "commission_fee"
    - "phone"
    - "mobile"
    - "mobile2"
    - "bic"
    - "fax"
    - "iban"
    - "description"
    - "org_type"
    - "uid"
src_eff: "dss_load_date"
src_ldts: "dss_load_date"
src_source: "dss_record_source"
{%- endset -%}

{% set metadata_dict = fromyaml(yaml_metadata) %}

{{ automate_dv.sat(
    src_pk=metadata_dict["src_pk"],
    src_hashdiff=metadata_dict["src_hashdiff"],
    src_payload=metadata_dict["src_payload"],
    src_eff=metadata_dict["src_eff"],
    src_ldts=metadata_dict["src_ldts"],
    src_source=metadata_dict["src_source"],
    source_model=metadata_dict["source_model"]
) }}
