{#
    Satellite: sat_rechnung
    Parent Hub: hub_rechnung
    Source: werkportal_rechnung
    Payload: date_created, date_updated, subscription, name, state, deductions_description, gross, invoicing_period_year, project, invoice_date, date_payed, description, advance_payment, date_payed_internally, payed, contractor, client, sum_goal, credit_period, deductions, sum_payed, hours_worked, subtractions, credit_rating_check, discount, ordering, createdby, member, pay_target_date, u_amount, comission_amount
    
    Generated by Entity Designer using automate_dv.sat macro
    @see https://automate-dv.readthedocs.io/en/latest/tutorial/tut_satellites/
#}

{{ config(
    materialized='incremental',
    as_columnstore=false,
    post_hook="{{ update_satellite_current_flag(this, 'hk_rechnung') }}"
) }}

{%- set yaml_metadata -%}
source_model: "werkportal_rechnung"
src_pk: "hk_rechnung"
src_hashdiff: 
  source_column: "hd_rechnung"
  alias: "hashdiff"
src_payload: 
    - "date_created"
    - "date_updated"
    - "subscription"
    - "name"
    - "state"
    - "deductions_description"
    - "gross"
    - "invoicing_period_year"
    - "project"
    - "invoice_date"
    - "date_payed"
    - "description"
    - "advance_payment"
    - "date_payed_internally"
    - "payed"
    - "contractor"
    - "client"
    - "sum_goal"
    - "credit_period"
    - "deductions"
    - "sum_payed"
    - "hours_worked"
    - "subtractions"
    - "credit_rating_check"
    - "discount"
    - "ordering"
    - "createdby"
    - "member"
    - "pay_target_date"
    - "u_amount"
    - "comission_amount"
src_eff: "dss_load_date"
src_ldts: "dss_load_date"
src_source: "dss_record_source"
{%- endset -%}

{% set metadata_dict = fromyaml(yaml_metadata) %}

{{ automate_dv.sat(
    src_pk=metadata_dict["src_pk"],
    src_hashdiff=metadata_dict["src_hashdiff"],
    src_payload=metadata_dict["src_payload"],
    src_eff=metadata_dict["src_eff"],
    src_ldts=metadata_dict["src_ldts"],
    src_source=metadata_dict["src_source"],
    source_model=metadata_dict["source_model"]
) }}
