{#
    Dependent Child Satellite: sat_contact_contractor_dc
    Parent Link: link_contact_contractor
    DCK Columns: name, email1
    Payload: name, email1, date_created, date_updated, subscription, state, title, email2, mobile1, mobile2, phone, fax, contact_function_name, company_supplier, company_client
    Source: werkportal_contact
    
    A Dependent Child Satellite tracks changes to link relationships
    that require additional keys (DCKs) for uniqueness.
    The Link Hash Key + DCK columns form the composite primary key.
    
    Generated by Entity Designer using automate_dv.sat macro
    @see https://automate-dv.readthedocs.io/en/latest/tutorial/tut_dep_child/
#}

{{ config(
    materialized='incremental',
    as_columnstore=false
) }}

{%- set yaml_metadata -%}
source_model: "werkportal_contact"
src_pk: "hk_link_contact_contractor"
src_hashdiff: 
  source_column: "hd_contact_contractor_dc"
  alias: "hashdiff"
src_payload: 
    - "name"
    - "email1"
    - "date_created"
    - "date_updated"
    - "subscription"
    - "state"
    - "title"
    - "email2"
    - "mobile1"
    - "mobile2"
    - "phone"
    - "fax"
    - "contact_function_name"
    - "company_supplier"
    - "company_client"
src_eff: "dss_load_date"
src_ldts: "dss_load_date"
src_source: "dss_record_source"
{%- endset -%}

{% set metadata_dict = fromyaml(yaml_metadata) %}

{{ automate_dv.sat(
    src_pk=metadata_dict["src_pk"],
    src_hashdiff=metadata_dict["src_hashdiff"],
    src_payload=metadata_dict["src_payload"],
    src_eff=metadata_dict["src_eff"],
    src_ldts=metadata_dict["src_ldts"],
    src_source=metadata_dict["src_source"],
    source_model=metadata_dict["source_model"]
) }}
