{#
    Satellite: sat_contacts
    Parent Hub: hub_contacts
    Source: werkportal_contacts
    Payload: subscription, date_created, date_updated, name, state, title, email1, email2, mobile1, mobile2, phone, fax, contact_function_name, company_supplier, company_contractor, contact_function_id
    
    Generated by Entity Designer using automate_dv.sat macro
    @see https://automate-dv.readthedocs.io/en/latest/tutorial/tut_satellites/
#}

{{ config(
    materialized='incremental',
    as_columnstore=false
) }}

{%- set yaml_metadata -%}
source_model: "werkportal_contacts"
src_pk: "hk_contacts"
src_hashdiff: 
  source_column: "hd_contacts"
  alias: "hashdiff"
src_payload: 
    - "subscription"
    - "date_created"
    - "date_updated"
    - "name"
    - "state"
    - "title"
    - "email1"
    - "email2"
    - "mobile1"
    - "mobile2"
    - "phone"
    - "fax"
    - "contact_function_name"
    - "company_supplier"
    - "company_contractor"
    - "contact_function_id"
src_eff: "dss_load_date"
src_ldts: "dss_load_date"
src_source: "dss_record_source"
{%- endset -%}

{% set metadata_dict = fromyaml(yaml_metadata) %}

{{ automate_dv.sat(
    src_pk=metadata_dict["src_pk"],
    src_hashdiff=metadata_dict["src_hashdiff"],
    src_payload=metadata_dict["src_payload"],
    src_eff=metadata_dict["src_eff"],
    src_ldts=metadata_dict["src_ldts"],
    src_source=metadata_dict["src_source"],
    source_model=metadata_dict["source_model"]
) }}
