{#
    Satellite: sat_vorgang
    Parent Hub: hub_vorgang
    Source: jira_vorgang
    Payload: issue_key, issue_type_id, issue_status_id, summary, priority, work_ratio, resolution, project_id, reporter_account_id, time_spent, time_spent_with_subtasks, original_estimate, original_estimate_with_subtasks, remaining_estimate, remaining_estimate_with_subtasks, parent_issue_id
    
    Generated by Entity Designer using automate_dv.sat macro
    @see https://automate-dv.readthedocs.io/en/latest/tutorial/tut_satellites/
#}

{{ config(
    materialized='incremental',
    as_columnstore=false,
    post_hook="{{ update_satellite_current_flag(this, 'hk_vorgang') }}"
) }}

{%- set yaml_metadata -%}
source_model: "jira_vorgang"
src_pk: "hk_vorgang"
src_hashdiff: 
  source_column: "hd_vorgang"
  alias: "hashdiff"
src_payload: 
    - "issue_key"
    - "issue_type_id"
    - "issue_status_id"
    - "summary"
    - "priority"
    - "work_ratio"
    - "resolution"
    - "project_id"
    - "reporter_account_id"
    - "time_spent"
    - "time_spent_with_subtasks"
    - "original_estimate"
    - "original_estimate_with_subtasks"
    - "remaining_estimate"
    - "remaining_estimate_with_subtasks"
    - "parent_issue_id"
src_eff: "dss_load_date"
src_ldts: "dss_load_date"
src_source: "dss_record_source"
{%- endset -%}

{% set metadata_dict = fromyaml(yaml_metadata) %}

{{ automate_dv.sat(
    src_pk=metadata_dict["src_pk"],
    src_hashdiff=metadata_dict["src_hashdiff"],
    src_payload=metadata_dict["src_payload"],
    src_eff=metadata_dict["src_eff"],
    src_ldts=metadata_dict["src_ldts"],
    src_source=metadata_dict["src_source"],
    source_model=metadata_dict["source_model"]
) }}
