{#
    Link: link_contacts_company_client
    Source Hub: hub_contacts
    Target Hub: werkportal.hub_company_client
    Driving Key: company_client
    Source: werkportal_contacts
    
    Generated by Entity Designer using automate_dv.link macro
    @see https://automate-dv.readthedocs.io/en/latest/tutorial/tut_links/
#}

{{ config(
    materialized='incremental',
    as_columnstore=false
) }}

{%- set yaml_metadata -%}
source_model: "werkportal_contacts"
src_pk: "hk_link_contacts_company_client"
src_fk:
    - "hk_contacts"
    - "hk_company_client"
src_ldts: "dss_load_date"
src_source: "dss_record_source"
{%- endset -%}

{% set metadata_dict = fromyaml(yaml_metadata) %}

{{ automate_dv.link(
    src_pk=metadata_dict["src_pk"],
    src_fk=metadata_dict["src_fk"],
    src_ldts=metadata_dict["src_ldts"],
    src_source=metadata_dict["src_source"],
    source_model=metadata_dict["source_model"]
) }}
