{#
    Link: link_contact_contractor
    Parent Hub: werkportal.hub_contractor
    Dependent Child: contact (no own hub)
    Driving Key: company_contractor
    Link Type: Dependent Child Link (Pure DC)
    - Source entity has no own Business Key
    - Identified by: Target FK (company_contractor) + DCK (name, email1)
    - Link PK hash includes DCK columns (calculated in staging)
    - DCK values are stored in the DC Satellite, not the link
    Source: werkportal_contact
    
    Note: In automate_dv, links don't store payload columns.
    DCK columns are only used for the link hash calculation in staging.
    The actual DCK values are stored in the DC Satellite.
    
    Generated by Entity Designer using automate_dv.link macro
    @see https://automate-dv.readthedocs.io/en/latest/tutorial/tut_links/
#}

{{ config(
    materialized='incremental',
    as_columnstore=false
) }}

{%- set yaml_metadata -%}
source_model: "werkportal_contact"
src_pk: "hk_link_contact_contractor"
src_fk: "hk_contractor"
src_ldts: "dss_load_date"
src_source: "dss_record_source"
{%- endset -%}

{% set metadata_dict = fromyaml(yaml_metadata) %}

{{ automate_dv.link(
    src_pk=metadata_dict["src_pk"],
    src_fk=metadata_dict["src_fk"],
    src_ldts=metadata_dict["src_ldts"],
    src_source=metadata_dict["src_source"],
    source_model=metadata_dict["source_model"]
) }}
