{{
  config(
    materialized='view',
    schema='vault_werkportal'
  )
}}

{#
  Virtual Hub View for Lambda Vault Pattern
  =========================================
  Combines persisted Hub data with real-time delta data for near-real-time queries.
  
  Base Staging: werkportal_rechnung (batch-loaded, persisted)
  Delta Staging: werkportal_rechnung_delta (real-time API/streaming)
  
  Generated by Entity Designer - Lambda Vault
#}

WITH base_hub AS (
  SELECT DISTINCT
    base.hk_rechnung,
    base.object_id,
    base.dss_load_date,
    base.dss_record_source
  FROM {{ ref('hub_rechnung') }} base
),

delta_staging AS (
  SELECT DISTINCT
    delta.hk_rechnung_delta AS hk_rechnung,
    delta.object_id,
    delta.dss_load_date,
    delta.dss_record_source
  FROM {{ ref('werkportal_rechnung_delta') }} delta
  WHERE delta.hk_rechnung_delta NOT IN (SELECT hk_rechnung FROM base_hub)
)

SELECT * FROM base_hub
UNION ALL
SELECT * FROM delta_staging
