{{
  config(
    materialized='view',
    schema='vault_werkportal'
  )
}}

{#
  Virtual Satellite View for Lambda Vault Pattern
  ===============================================
  Combines persisted Satellite data with real-time delta data for near-real-time queries.
  
  dss_is_current is DYNAMICALLY calculated based on the latest dss_load_date per entity.
  This ensures delta records correctly mark base records as non-current.
  
  Base Satellite: sat_rechnung (batch-loaded, persisted)
  Delta Staging: werkportal_rechnung_delta (real-time API/streaming)
  
  Generated by Entity Designer - Lambda Vault
#}

WITH base_sat AS (
  SELECT
    base.hk_rechnung,
    base.hashdiff,
    base.date_created,
    base.date_updated,
    base.subscription,
    base.name,
    base.state,
    base.deductions_description,
    base.gross,
    base.invoicing_period_year,
    base.project,
    base.invoice_date,
    base.date_payed,
    base.description,
    base.advance_payment,
    base.date_payed_internally,
    base.payed,
    base.contractor,
    base.client,
    base.sum_goal,
    base.credit_period,
    base.deductions,
    base.sum_payed,
    base.hours_worked,
    base.subtractions,
    base.credit_rating_check,
    base.discount,
    base.ordering,
    base.createdby,
    base.member,
    base.pay_target_date,
    base.u_amount,
    base.comission_amount,
    base.dss_load_date,
    base.dss_record_source
  FROM {{ ref('sat_rechnung') }} base
),

delta_staging AS (
  -- Delta records that are newer than what's in the satellite
  SELECT
    delta.hk_rechnung_delta AS hk_rechnung,
    delta.hd_rechnung_delta AS hashdiff,
    delta.date_created,
    delta.date_updated,
    delta.subscription_object_id AS subscription,
    delta.name,
    delta.state,
    delta.deductions_description,
    delta.gross,
    delta.invoicing_period_year,
    delta.project_object_id AS project,
    delta.invoice_date,
    NULL AS date_payed,
    delta.description,
    delta.advance_payment,
    NULL AS date_payed_internally,
    delta.payed,
    delta.contractor_object_id AS contractor,
    delta.client_object_id AS client,
    delta.sum_goal,
    delta.credit_period,
    delta.deductions,
    delta.sum_payed,
    delta.hours_worked,
    delta.subtractions,
    delta.credit_rating_check,
    delta.discount,
    delta.ordering,
    delta.createdby_object_id AS createdby,
    delta.member_object_id AS member,
    delta.pay_target_date,
    delta.u_amount,
    delta.comission_amount,
    delta.dss_load_date,
    delta.dss_record_source
  FROM {{ ref('werkportal_rechnung_delta') }} delta
  WHERE NOT EXISTS (
    SELECT 1 FROM base_sat b 
    WHERE b.hk_rechnung = delta.hk_rechnung_delta
      AND b.hashdiff = delta.hd_rechnung_delta
  )
),

combined AS (
  SELECT * FROM base_sat
  UNION ALL
  SELECT * FROM delta_staging
),

ranked AS (
  -- Calculate dss_is_current dynamically: only the latest record per entity is current
  SELECT
    hk_rechnung,
    hashdiff,
    date_created,
    date_updated,
    subscription,
    name,
    state,
    deductions_description,
    gross,
    invoicing_period_year,
    project,
    invoice_date,
    date_payed,
    description,
    advance_payment,
    date_payed_internally,
    payed,
    contractor,
    client,
    sum_goal,
    credit_period,
    deductions,
    sum_payed,
    hours_worked,
    subtractions,
    credit_rating_check,
    discount,
    ordering,
    createdby,
    member,
    pay_target_date,
    u_amount,
    comission_amount,
    dss_load_date,
    dss_record_source,
    ROW_NUMBER() OVER (
      PARTITION BY hk_rechnung 
      ORDER BY dss_load_date DESC
    ) AS rn,
    LEAD(dss_load_date) OVER (
      PARTITION BY hk_rechnung 
      ORDER BY dss_load_date
    ) AS next_load_date
  FROM combined
)

SELECT
  hk_rechnung,
  hashdiff,
  date_created,
  date_updated,
  subscription,
  name,
  state,
  deductions_description,
  gross,
  invoicing_period_year,
  project,
  invoice_date,
  date_payed,
  description,
  advance_payment,
  date_payed_internally,
  payed,
  contractor,
  client,
  sum_goal,
  credit_period,
  deductions,
  sum_payed,
  hours_worked,
  subtractions,
  credit_rating_check,
  discount,
  ordering,
  createdby,
  member,
  pay_target_date,
  u_amount,
  comission_amount,
  dss_load_date,
  dss_record_source,
  CASE WHEN rn = 1 THEN 'Y' ELSE 'N' END AS dss_is_current,
  next_load_date AS dss_end_date
FROM ranked
