/**
 * Entity Generator Service
 * 
 * Generates Hub, Satellite, and Link SQL files for Data Vault 2.0
 * Using automate_dv macros for standardized patterns
 * 
 * @see https://automate-dv.readthedocs.io/en/latest/tutorial/
 */

import * as path from 'path';
import * as fs from 'fs/promises';
import { EntityDesignConfig, DesignerColumnDefinition, GeneratedFile, GenerationResult } from '../types';

/**
 * Generate Data Vault objects from entity design configuration
 */
export async function generateDataVaultObjects(
  config: EntityDesignConfig,
  projectPath: string,
  targets: ('hub' | 'satellite' | 'links')[]
): Promise<GenerationResult> {
  const generatedFiles: GeneratedFile[] = [];
  const errors: string[] = [];

  try {
    // Map UI column types to internal types (handle both old and new naming)
    const businessKeys = config.columns.filter(c => 
      c.columnType === 'business_key' || c.columnType === 'hub'
    );
    const attributes = config.columns.filter(c => 
      (c.columnType === 'attribute' || c.columnType === 'satellite') &&
      // Exclude hash columns from payload - they are handled separately
      !c.name.toLowerCase().startsWith('hk_') &&
      !c.name.toLowerCase().startsWith('hd_')
    );
    const foreignKeys = config.columns.filter(c => 
      c.columnType === 'foreign_key' || c.columnType === 'link'
    );

    // Validate basic requirements
    if (businessKeys.length === 0 && targets.includes('hub')) {
      errors.push('At least one Business Key is required for Hub generation');
      return { success: false, files: [], errors };
    }

    // Generate Hub using automate_dv.hub macro
    if (targets.includes('hub')) {
      const hubFile = await generateHub(config, businessKeys, projectPath);
      generatedFiles.push(hubFile);
    }

    // Generate Satellite using automate_dv.sat macro
    if (targets.includes('satellite') && attributes.length > 0) {
      const satFile = await generateSatellite(config, attributes, projectPath);
      generatedFiles.push(satFile);
    }

    // Generate Links using automate_dv.link macro
    if (targets.includes('links') && foreignKeys.length > 0) {
      for (const fk of foreignKeys) {
        if (fk.foreignKeyTarget) {
          const linkFile = await generateLink(config, fk, businessKeys, projectPath);
          generatedFiles.push(linkFile);
        }
      }
    }

    return {
      success: errors.length === 0,
      files: generatedFiles,
      errors
    };

  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : String(error);
    errors.push(`Generation failed: ${errorMessage}`);
    return { success: false, files: generatedFiles, errors };
  }
}

/**
 * Generate Hub SQL file using automate_dv.hub macro
 * @see https://automate-dv.readthedocs.io/en/latest/tutorial/tut_hubs/
 */
async function generateHub(
  config: EntityDesignConfig,
  businessKeys: DesignerColumnDefinition[],
  projectPath: string
): Promise<GeneratedFile> {
  const { concept, entityName } = config;
  const hubName = `hub_${entityName}`;
  const hashKeyName = `hk_${entityName.toLowerCase()}`;
  const stagingRef = `${concept}_${entityName}`;
  
  // Build natural key list - can be single or composite (lowercase to match staging)
  const naturalKeys = businessKeys.map(bk => `"${bk.name.toLowerCase()}"`);
  const nkConfig = naturalKeys.length === 1 
    ? naturalKeys[0]
    : `\n    - ${naturalKeys.join('\n    - ')}`;

  const sql = `{#
    Hub: ${hubName}
    Source: ${stagingRef}
    Business Keys: ${businessKeys.map(bk => bk.name).join(', ')}
    
    Generated by Entity Designer using automate_dv.hub macro
    @see https://automate-dv.readthedocs.io/en/latest/tutorial/tut_hubs/
#}

{{ config(
    materialized='incremental',
    as_columnstore=false
) }}

{%- set yaml_metadata -%}
source_model: "${stagingRef}"
src_pk: "${hashKeyName}"
src_nk: ${nkConfig}
src_ldts: "dss_load_date"
src_source: "dss_record_source"
{%- endset -%}

{% set metadata_dict = fromyaml(yaml_metadata) %}

{{ automate_dv.hub(
    src_pk=metadata_dict["src_pk"],
    src_nk=metadata_dict["src_nk"],
    src_ldts=metadata_dict["src_ldts"],
    src_source=metadata_dict["src_source"],
    source_model=metadata_dict["source_model"]
) }}
`;

  const filePath = path.join(
    projectPath,
    'models',
    'raw_vault',
    concept,
    'hubs',
    `${hubName}.sql`
  );

  // Ensure directory exists
  await fs.mkdir(path.dirname(filePath), { recursive: true });
  
  // Write file
  await fs.writeFile(filePath, sql, 'utf-8');

  return { path: filePath, content: sql, type: 'hub' };
}

/**
 * Generate Satellite SQL file using automate_dv.sat macro
 * @see https://automate-dv.readthedocs.io/en/latest/tutorial/tut_satellites/
 */
async function generateSatellite(
  config: EntityDesignConfig,
  attributes: DesignerColumnDefinition[],
  projectPath: string
): Promise<GeneratedFile> {
  const { concept, entityName } = config;
  const satName = `sat_${entityName}`;
  const hashKeyName = `hk_${entityName.toLowerCase()}`;
  const hashDiffName = `hd_${entityName.toLowerCase()}`;
  const stagingRef = `${concept}_${entityName}`;

  // Build payload list (lowercase to match staging)
  const payloadColumns = attributes.map(a => `"${a.name.toLowerCase()}"`);
  const payloadConfig = payloadColumns.length === 1
    ? payloadColumns[0]
    : `\n    - ${payloadColumns.join('\n    - ')}`;

  const sql = `{#
    Satellite: ${satName}
    Parent Hub: hub_${entityName}
    Source: ${stagingRef}
    Payload: ${attributes.map(a => a.name).join(', ')}
    
    Generated by Entity Designer using automate_dv.sat macro
    @see https://automate-dv.readthedocs.io/en/latest/tutorial/tut_satellites/
#}

{{ config(
    materialized='incremental',
    as_columnstore=false
) }}

{%- set yaml_metadata -%}
source_model: "${stagingRef}"
src_pk: "${hashKeyName}"
src_hashdiff: 
  source_column: "${hashDiffName}"
  alias: "hashdiff"
src_payload: ${payloadConfig}
src_eff: "dss_load_date"
src_ldts: "dss_load_date"
src_source: "dss_record_source"
{%- endset -%}

{% set metadata_dict = fromyaml(yaml_metadata) %}

{{ automate_dv.sat(
    src_pk=metadata_dict["src_pk"],
    src_hashdiff=metadata_dict["src_hashdiff"],
    src_payload=metadata_dict["src_payload"],
    src_eff=metadata_dict["src_eff"],
    src_ldts=metadata_dict["src_ldts"],
    src_source=metadata_dict["src_source"],
    source_model=metadata_dict["source_model"]
) }}
`;

  const filePath = path.join(
    projectPath,
    'models',
    'raw_vault',
    concept,
    'satellites',
    `${satName}.sql`
  );

  // Ensure directory exists
  await fs.mkdir(path.dirname(filePath), { recursive: true });
  
  // Write file
  await fs.writeFile(filePath, sql, 'utf-8');

  return { path: filePath, content: sql, type: 'satellite' };
}

/**
 * Generate Link SQL file using automate_dv.link macro
 * @see https://automate-dv.readthedocs.io/en/latest/tutorial/tut_links/
 */
async function generateLink(
  config: EntityDesignConfig,
  foreignKey: DesignerColumnDefinition,
  businessKeys: DesignerColumnDefinition[],
  projectPath: string
): Promise<GeneratedFile> {
  const { concept, entityName } = config;
  const targetHubFull = foreignKey.foreignKeyTarget!;
  
  // Parse target hub - can be "concept.hub_name" or just "hub_name"
  let targetConcept: string;
  let targetHub: string;
  if (targetHubFull.includes('.')) {
    [targetConcept, targetHub] = targetHubFull.split('.');
  } else {
    targetConcept = concept;
    targetHub = targetHubFull;
  }
  
  // Extract target entity name from hub name (e.g., "hub_country" -> "country")
  const targetEntity = targetHub.replace('hub_', '');
  
  const linkName = `link_${entityName}_${targetEntity}`;
  const linkHashKey = `hk_${linkName.toLowerCase()}`;
  const sourceHashKey = `hk_${entityName.toLowerCase()}`;
  const targetHashKey = `hk_${targetEntity.toLowerCase()}`;
  const stagingRef = `${concept}_${entityName}`;

  const sql = `{#
    Link: ${linkName}
    Source Hub: hub_${entityName}
    Target Hub: ${targetConcept}.${targetHub}
    Driving Key: ${foreignKey.name}
    Source: ${stagingRef}
    
    Generated by Entity Designer using automate_dv.link macro
    @see https://automate-dv.readthedocs.io/en/latest/tutorial/tut_links/
#}

{{ config(
    materialized='incremental',
    as_columnstore=false
) }}

{%- set yaml_metadata -%}
source_model: "${stagingRef}"
src_pk: "${linkHashKey}"
src_fk:
    - "${sourceHashKey}"
    - "${targetHashKey}"
src_ldts: "dss_load_date"
src_source: "dss_record_source"
{%- endset -%}

{% set metadata_dict = fromyaml(yaml_metadata) %}

{{ automate_dv.link(
    src_pk=metadata_dict["src_pk"],
    src_fk=metadata_dict["src_fk"],
    src_ldts=metadata_dict["src_ldts"],
    src_source=metadata_dict["src_source"],
    source_model=metadata_dict["source_model"]
) }}
`;

  const filePath = path.join(
    projectPath,
    'models',
    'raw_vault',
    concept,
    'links',
    `${linkName}.sql`
  );

  // Ensure directory exists
  await fs.mkdir(path.dirname(filePath), { recursive: true });
  
  // Write file
  await fs.writeFile(filePath, sql, 'utf-8');

  return { path: filePath, content: sql, type: 'link' };
}

/**
 * Generate YAML schema documentation for generated models
 */
export async function generateSchemaYaml(
  config: EntityDesignConfig,
  generatedFiles: GeneratedFile[],
  projectPath: string
): Promise<GeneratedFile> {
  const { concept, entityName } = config;
  const businessKeys = config.columns.filter(c => 
    c.columnType === 'business_key' || c.columnType === 'hub'
  );
  const attributes = config.columns.filter(c => 
    c.columnType === 'attribute' || c.columnType === 'satellite'
  );

  // Build YAML content
  let yamlContent = `version: 2

models:`;

  // Add Hub model
  if (generatedFiles.some(f => f.type === 'hub')) {
    yamlContent += `
  - name: hub_${entityName}
    description: |
      Hub for ${entityName} entity.
      Generated by Entity Designer using automate_dv.hub macro.
    columns:
      - name: hk_${entityName.toLowerCase()}
        description: Hash Key (Primary Key)
        data_type: char(64)
        tests:
          - not_null
          - unique`;
    
    for (const bk of businessKeys) {
      yamlContent += `
      - name: ${bk.name.toLowerCase()}
        description: Business Key
        data_type: ${bk.dataType || 'nvarchar(max)'}
        tests:
          - not_null`;
    }

    yamlContent += `
      - name: dss_load_date
        description: Load timestamp
        data_type: datetime2(7)
        tests:
          - not_null
      - name: dss_record_source
        description: Data source identifier
        data_type: varchar(100)
        tests:
          - not_null`;
  }

  // Add Satellite model
  if (generatedFiles.some(f => f.type === 'satellite')) {
    yamlContent += `

  - name: sat_${entityName}
    description: |
      Satellite for ${entityName} attributes.
      Generated by Entity Designer using automate_dv.sat macro.
    columns:
      - name: hk_${entityName.toLowerCase()}
        description: Hash Key (FK to Hub)
        data_type: char(64)
        tests:
          - not_null
      - name: hashdiff
        description: Hash Diff for change detection (aliased from hd_${entityName.toLowerCase()})
        data_type: char(64)
        tests:
          - not_null`;

    for (const attr of attributes) {
      yamlContent += `
      - name: ${attr.name.toLowerCase()}
        description: ${attr.name} attribute
        data_type: ${attr.dataType || 'nvarchar(max)'}`;
    }

    yamlContent += `
      - name: effective_from
        description: Business effectivity date
        data_type: datetime2(7)
      - name: dss_load_date
        description: Load timestamp
        data_type: datetime2(7)
        tests:
          - not_null
      - name: dss_record_source
        description: Data source identifier
        data_type: varchar(100)
        tests:
          - not_null`;
  }

  // Add Link models
  const linkFiles = generatedFiles.filter(f => f.type === 'link');
  for (const linkFile of linkFiles) {
    const linkName = path.basename(linkFile.path, '.sql');
    yamlContent += `

  - name: ${linkName}
    description: |
      Link relationship.
      Generated by Entity Designer using automate_dv.link macro.
    columns:
      - name: hk_${linkName.toLowerCase()}
        description: Link Hash Key (Primary Key)
        data_type: char(64)
        tests:
          - not_null
          - unique
      - name: hk_${entityName.toLowerCase()}
        description: FK to source Hub
        data_type: char(64)
        tests:
          - not_null
      - name: dss_load_date
        description: Load timestamp
        data_type: datetime2(7)
        tests:
          - not_null
      - name: dss_record_source
        description: Data source identifier
        data_type: varchar(100)
        tests:
          - not_null`;
  }

  yamlContent += '\n';

  const filePath = path.join(
    projectPath,
    'models',
    'raw_vault',
    concept,
    `_${concept}__models.yml`
  );

  // Check if file exists and merge if needed
  try {
    const existingContent = await fs.readFile(filePath, 'utf-8');
    
    // Parse model names we're trying to add
    const newModelNames = new Set<string>();
    if (generatedFiles.some(f => f.type === 'hub')) {
      newModelNames.add(`hub_${entityName}`);
    }
    if (generatedFiles.some(f => f.type === 'satellite')) {
      newModelNames.add(`sat_${entityName}`);
    }
    for (const linkFile of linkFiles) {
      newModelNames.add(path.basename(linkFile.path, '.sql'));
    }
    
    // Check which models already exist in the YAML
    const existingModelMatches = existingContent.matchAll(/^\s*-\s*name:\s*(\S+)/gm);
    const existingModels = new Set([...existingModelMatches].map(m => m[1]));
    
    // Filter to only new models that don't exist yet
    const modelsToAdd: string[] = [];
    for (const modelName of newModelNames) {
      if (!existingModels.has(modelName)) {
        modelsToAdd.push(modelName);
      }
    }
    
    if (modelsToAdd.length === 0) {
      console.log('[Entity Generator] All models already exist in YAML, skipping');
      return { path: filePath, content: existingContent, type: 'schema' };
    }
    
    // Build YAML for only the new models
    let newModelsYaml = '';
    
    if (modelsToAdd.includes(`hub_${entityName}`)) {
      newModelsYaml += buildHubYaml(entityName, businessKeys);
    }
    if (modelsToAdd.includes(`sat_${entityName}`)) {
      newModelsYaml += buildSatelliteYaml(entityName, attributes);
    }
    for (const linkFile of linkFiles) {
      const linkName = path.basename(linkFile.path, '.sql');
      if (modelsToAdd.includes(linkName)) {
        newModelsYaml += buildLinkYaml(linkName, entityName, linkFile);
      }
    }
    
    // Append new models to existing content (before final newline)
    const mergedContent = existingContent.trimEnd() + '\n' + newModelsYaml;
    await fs.writeFile(filePath, mergedContent, 'utf-8');
    console.log(`[Entity Generator] Merged ${modelsToAdd.length} new models into YAML`);
    
    return { path: filePath, content: mergedContent, type: 'schema' };
    
  } catch {
    // File doesn't exist, create it
    await fs.mkdir(path.dirname(filePath), { recursive: true });
    await fs.writeFile(filePath, yamlContent, 'utf-8');
    console.log('[Entity Generator] Created new YAML file');
  }

  return { path: filePath, content: yamlContent, type: 'schema' };
}

/**
 * Build YAML content for a Hub model
 */
function buildHubYaml(entityName: string, businessKeys: DesignerColumnDefinition[]): string {
  let yaml = `
  - name: hub_${entityName}
    description: |
      Hub for ${entityName} entity.
      Generated by Entity Designer using automate_dv.hub macro.
    columns:
      - name: hk_${entityName.toLowerCase()}
        description: Hash Key (Primary Key)
        data_type: char(64)
        tests:
          - not_null
          - unique`;
  
  for (const bk of businessKeys) {
    yaml += `
      - name: ${bk.name.toLowerCase()}
        description: Business Key
        data_type: ${bk.dataType || 'NVARCHAR(MAX)'}
        tests:
          - not_null`;
  }

  yaml += `
      - name: dss_load_date
        description: Load timestamp
        data_type: datetime2(7)
        tests:
          - not_null
      - name: dss_record_source
        description: Data source identifier
        data_type: varchar(100)
        tests:
          - not_null
`;
  return yaml;
}

/**
 * Build YAML content for a Satellite model
 */
function buildSatelliteYaml(entityName: string, attributes: DesignerColumnDefinition[]): string {
  let yaml = `
  - name: sat_${entityName}
    description: |
      Satellite for ${entityName} attributes.
      Generated by Entity Designer using automate_dv.sat macro.
    columns:
      - name: hk_${entityName.toLowerCase()}
        description: Hash Key (FK to Hub)
        data_type: char(64)
        tests:
          - not_null
      - name: hashdiff
        description: Hash Diff for change detection
        data_type: char(64)
        tests:
          - not_null`;

  for (const attr of attributes) {
    yaml += `
      - name: ${attr.name.toLowerCase()}
        description: ${attr.name} attribute
        data_type: ${attr.dataType || 'NVARCHAR(MAX)'}`;
  }

  yaml += `
      - name: effective_from
        description: Business effectivity date
        data_type: datetime2(7)
      - name: dss_load_date
        description: Load timestamp
        data_type: datetime2(7)
        tests:
          - not_null
      - name: dss_record_source
        description: Data source identifier
        data_type: varchar(100)
        tests:
          - not_null
`;
  return yaml;
}

/**
 * Build YAML content for a Link model
 */
function buildLinkYaml(linkName: string, sourceEntityName: string, linkFile: GeneratedFile): string {
  // Extract target hub from link file content
  const fkMatch = linkFile.content.match(/src_fk:\s*\n\s*-\s*"([^"]+)"\s*\n\s*-\s*"([^"]+)"/);
  const fks = fkMatch ? [fkMatch[1], fkMatch[2]] : [`hk_${sourceEntityName.toLowerCase()}`];
  
  let yaml = `
  - name: ${linkName}
    description: |
      Link relationship.
      Generated by Entity Designer using automate_dv.link macro.
    columns:
      - name: hk_${linkName.toLowerCase()}
        description: Link Hash Key (Primary Key)
        data_type: char(64)
        tests:
          - not_null
          - unique`;

  for (const fk of fks) {
    yaml += `
      - name: ${fk}
        description: FK to Hub
        data_type: char(64)
        tests:
          - not_null`;
  }

  yaml += `
      - name: dss_load_date
        description: Load timestamp
        data_type: datetime2(7)
        tests:
          - not_null
      - name: dss_record_source
        description: Data source identifier
        data_type: varchar(100)
        tests:
          - not_null
`;
  return yaml;
}
