version: 2
models:
  - name: stg_company
    description: Unified Staging Model für alle Companies (Client, Contractor, Supplier)
    columns:
      - name: hk_company
        description: Hash Key (SHA256 von object_id + source_table)
        tests:
          - not_null
      - name: hd_company
        description: Hash Diff für Change Detection
        tests:
          - not_null
      - name: object_id
        description: Business Key aus Quellsystem
        tests:
          - not_null
      - name: source_table
        description: Quelltabelle (wp_company_client/contractor/supplier)
        tests:
          - not_null
      - name: role_code
        description: Rolle (CLIENT, CONTRACTOR, SUPPLIER)
        tests:
          - not_null
          - accepted_values:
              values:
                - CLIENT
                - CONTRACTOR
                - SUPPLIER
  - name: stg_country
    description: Staging Model für Länder
    columns:
      - name: hk_country
        description: Hash Key (SHA256 von object_id)
        tests:
          - not_null
      - name: object_id
        description: Business Key
        tests:
          - not_null
  - name: hub_company
    description: Unified Hub für alle Unternehmen aus allen 3 Quellen
    columns:
      - name: hk_company
        description: Hash Key (Primary Key)
        tests:
          - not_null
          - unique
      - name: object_id
        description: Business Key aus Quellsystem
        tests:
          - not_null
      - name: source_table
        description: Quelltabelle
        tests:
          - not_null
      - name: dss_load_date
        description: Erstes Ladedatum
        tests:
          - not_null
      - name: dss_record_source
        description: Datenquelle
        tests:
          - not_null
  - name: hub_country
    description: Hub für Länder
    columns:
      - name: hk_country
        description: Hash Key (Primary Key)
        tests:
          - not_null
          - unique
      - name: object_id
        description: Business Key
        tests:
          - not_null
  - name: sat_company
    description: Satellite mit gemeinsamen Attributen aller Unternehmen
    columns:
      - name: hk_company
        description: Hash Key (FK zu hub_company)
        tests:
          - not_null
          - relationships:
              to: ref('hub_company')
              field: hk_company
      - name: hd_company
        description: Hash Diff für Change Detection
        tests:
          - not_null
  - name: sat_country
    description: Satellite mit Länder-Attributen
    columns:
      - name: hk_country
        description: Hash Key (FK zu hub_country)
        tests:
          - not_null
          - relationships:
              to: ref('hub_country')
              field: hk_country
  - name: sat_company_client_ext
    description: Erweiterter Satellite nur für Clients (freistellungsbescheinigung)
    columns:
      - name: hk_company
        description: Hash Key (FK zu hub_company)
        tests:
          - not_null
          - relationships:
              to: ref('hub_company')
              field: hk_company
  - name: link_company_role
    description: Link zwischen Company und Rolle
    columns:
      - name: hk_link_company_role
        description: Hash Key (Primary Key)
        tests:
          - not_null
          - unique
      - name: hk_company
        description: FK zu hub_company
        tests:
          - not_null
          - relationships:
              to: ref('hub_company')
              field: hk_company
      - name: hk_role
        description: FK zu ref_role (via role_code Hash)
        tests:
          - not_null
      - name: role_code
        description: Rolle (CLIENT, CONTRACTOR, SUPPLIER)
        tests:
          - not_null
  - name: link_company_country
    description: Link zwischen Company und Land
    columns:
      - name: hk_link_company_country
        description: Hash Key (Primary Key)
        tests:
          - not_null
          - unique
      - name: hk_company
        description: FK zu hub_company
        tests:
          - not_null
          - relationships:
              to: ref('hub_company')
              field: hk_company
      - name: hk_country
        description: FK zu hub_country
        tests:
          - not_null
          - relationships:
              to: ref('hub_country')
              field: hk_country
  - name: v_company_top5
    columns:
      - name: object_id
        tests:
          - not_null
          - unique
      - name: name
        tests:
          - not_null
      - name: hk_company
        tests:
          - not_null
          - unique
  - name: v_top10_customers
    columns:
      - name: hk_company
        tests:
          - not_null
          - unique
      - name: object_id
        tests:
          - not_null
      - name: name
        tests:
          - not_null
      - name: date_created
        tests:
          - not_null
  - name: v_countries
    columns:
      - name: object_id
        tests:
          - not_null
          - unique
      - name: name
        tests:
          - not_null
      - name: hk_country
        tests:
          - not_null
          - unique
  - name: v_company_current
    columns:
      - name: company_key
        tests:
          - not_null
          - unique
      - name: name
        tests:
          - not_null
      - name: state
        tests:
          - not_null
  - name: v_country_names
    columns:
      - name: country_name
        tests:
          - not_null
          - unique
  - name: v_country_current
    columns:
      - name: hk_country
        tests:
          - not_null
          - unique
      - name: object_id
        tests:
          - not_null
          - unique
      - name: name
        tests:
          - not_null
  - name: v_company_extended
    columns:
      - name: hk_company
        tests:
          - not_null
          - unique
      - name: company_id
        tests:
          - not_null
          - unique
      - name: company_name
        tests:
          - not_null
